apiVersion: v1
kind: ConfigMap
metadata:
  name: environment-config
  namespace: example
  labels:
    app: userservice
data:
  LOCAL_ROUTING_NUM: "883745000"
  PUB_KEY_PATH: /tmp/.ssh/publickey
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: accounts-db-config
  labels:
    app: userservice
  namespace: example
data:
  POSTGRES_DB: accounts-db
  POSTGRES_USER: accounts-admin
  POSTGRES_PASSWORD: accounts-pwd
  ACCOUNTS_DB_URI: postgresql://accounts-admin:accounts-pwd@accounts-db:5432/accounts-db
