apiVersion: v1
kind: Service
metadata:
  name: userservice
  namespace: example
  labels:
    app: userservice
spec:
  type: ClusterIP
  selector:
    app: userservice
  ports:
  - name: http
    port: 8080
    targetPort: 8080
