apiVersion: fn.kpt.dev/v1alpha1
kind: StarlarkRun
metadata: # kpt-merge: /set-app-image
  name: set-app-image
  annotations:
    config.kubernetes.io/local-config: "true"
    internal.kpt.dev/upstream-identifier: fn.kpt.dev|StarlarkRun|default|set-app-image
source: |-
  def set_name(resources):
    pkgName = ""
    isAbstractPackage = False
    for resource in resources:
      if resource["kind"] == "ConfigMap" and resource["metadata"]["name"] == "kptfile.kpt.dev" and resource["data"]["name"] == "example":
        isAbstractPackage = True
      if resource["kind"] == "Kptfile":
        pkgName = resource["metadata"]["name"]
    if not isAbstractPackage:
      # update resource name only if this is an abstract blueprint
      return
    if pkgName == "":
      fail("package must have a name.")
      return

    for resource in ctx.resource_list["items"]:
      if resource["kind"] == "StatefulSet":
        resource["metadata"]["name"] = pkgName
        currImgTag = resource["spec"]["template"]["spec"]["containers"][0]["image"].rsplit(":")[-1]
        resource["spec"]["template"]["spec"]["containers"][0]["image"]="gcr.io/bank-of-anthos-ci/"+pkgName+":"+currImgTag
  set_name(ctx.resource_list["items"])
